apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprod-log4j-deployment
  namespace: preprod-log4j
spec:
  replicas: 2
  selector:
    matchLabels:
      app: preprod-log4j
  template:
    metadata:
      labels:
        app: preprod-log4j
    spec:
      containers:
      - name: preprod-log4j
        image: teds2acr.azurecr.io/cicd-log4j:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
